travis:
  secure:
    BINSTAR_TOKEN: cPcT+JOzFZ1vjT+G7SpDKn0eT7WRC9gQay4eUx+XLF5716X92OXtRSQR8O+Cv6LJ+wqmND7SyCOCmbnXiSm9bjepiJWyeGD9ZgVR0x+eks84avMRvHdr0meI3ejiwCGjMaoFXy2/x9x8LncmBSZcg0kVYN6J9LNy8H489M+1fv3EM8kjkabuYXsc5Q3crWDVwgsEo+Odrpc0Gr14dWgxUzr6Af+DYjUpkbjZAph6sIjZf0xjIIinqtk9L8Azwr1kg4PfNSyQ4JRQyKp3tKWXa8sDzvUeYBMO/c7yYjM9l2LN2PTuaLces21QLAF41Crddnmq7qjtgtydYo18zWt2gLLH6UWmrsK0i2S5xFDcoo3TDLISxj/7RWYpTQnCm6cLuOY2I3maLc7kikUTHvaZ/+ZgAU5aueHM9UaFhvRNGU8JfZ2JXQr3kRuUlyFXhpJLbSTQz3+hiIa9a1QZ+IsCBGzYS5il2tm7Yg6eorECYS3tS7ydYfQcbuhNetdqHsxmi6NWPzlWDn3TUb3o49W/Bge+N4Fm7V8hebcXJEn8ouEwWbfG4GEw1bdIX4g8ftAZj7RcKQ6mlWBChTlN9pXClxW2HeE4CfrDJSm1xCZjQbODIQ8Qs9shmOyC3e/fPpDnu2Z2uB2+PehU0vyrGqBnQfl4lKYin936p6OAEu7Gu8o=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
